# Generated by Django 2.1.2 on 2018-10-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0008_auto_20181009_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200, null=True)),
                ('employees', models.ManyToManyField(to='employee.Employee')),
            ],
        ),
    ]
