# Generated by Django 2.1.1 on 2018-10-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_expense_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_employee', models.ManyToManyField(to='employee.Employee')),
            ],
        ),
    ]
