# Generated by Django 2.1.2 on 2018-10-09 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20181007_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='employees',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
