# Generated by Django 2.1.2 on 2018-10-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20181009_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
