# Generated by Django 2.1.2 on 2018-10-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20181009_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
